### ISSUE TITLE
Internal Server Error when trying to Export Experiment Data

### ISSUE THREAD

**Issue by jobrachem** [ctreffe/mortimer#98]
### Discussed in https://github.com/ctreffe/alfred/discussions/234

<div type='discussions-op-text'>

<sup>Originally posted by **Adsecularis** April 11, 2023</sup>
Hi,

we had an Internal Server Error when we tried to Export the Experiment Data in Mortimer.
As the bottom left of the mortimer website tells me, we run mortimer v0.8.13 & alfred v2.3.3.

As I say "had". I fixed it, but I would like you to double-check that and maybe it's helpful to others as well.

The "ssl-error.log" first gave me this:
```
[Sun Apr 09 19:28:35.439378 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702] mod_wsgi (pid=981527): Exception occurred processing WSGI script '/home/alfred/www/mortimer3/wsgi.py'.
[Sun Apr 09 19:28:35.439565 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702] Traceback (most recent call last):
[Sun Apr 09 19:28:35.439608 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]   File "/home/alfred/.virtualenvs/alfred3/lib/python3.8/site-packages/flask/app.py", line 2548, in __call__
[Sun Apr 09 19:28:35.439630 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]     return self.wsgi_app(environ, start_response)
[Sun Apr 09 19:28:35.439646 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]   File "/home/alfred/.virtualenvs/alfred3/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
[Sun Apr 09 19:28:35.439655 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]     response = self.handle_exception(e)
[Sun Apr 09 19:28:35.439677 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]   File "/home/alfred/.virtualenvs/alfred3/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
[Sun Apr 09 19:28:35.439687 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]     response = self.full_dispatch_request()
[Sun Apr 09 19:28:35.439702 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]   File "/home/alfred/.virtualenvs/alfred3/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Sun Apr 09 19:28:35.439718 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]     rv = self.handle_user_exception(e)
[Sun Apr 09 19:28:35.439733 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]   File "/home/alfred/.virtualenvs/alfred3/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Sun Apr 09 19:28:35.439748 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]     rv = self.dispatch_request()
[Sun Apr 09 19:28:35.439763 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]   File "/home/alfred/.virtualenvs/alfred3/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
[Sun Apr 09 19:28:35.439773 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Sun Apr 09 19:28:35.439793 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]   File "/home/alfred/.virtualenvs/alfred3/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
[Sun Apr 09 19:28:35.439803 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]     return current_app.ensure_sync(func)(*args, **kwargs)
[Sun Apr 09 19:28:35.439818 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]   File "/home/alfred/.virtualenvs/alfred3/lib/python3.8/site-packages/mortimer/web_experiments/routes.py", line 732, in export_main_data
[Sun Apr 09 19:28:35.439836 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702]     return send_file(
[Sun Apr 09 19:28:35.439863 2023] [wsgi:error] [pid 981527:tid 139986196502272] [remote 147.172.2.12:56702] TypeError: send_file() got an unexpected keyword argument 'attachment_filename'
```
Or in short: **TypeError: send_file() got an unexpected keyword argument 'attachment_filename'**

So, I went to /home/alfred/.virtualenvs/alfred3/lib/python3.8/site-packages/mortimer/web_experiments/routes.py 
and as this [StackOverflow thread](https://stackoverflow.com/questions/73276384/getting-an-error-attachment-filename-does-not-exist-in-my-docker-environment) suggested I replaced "attachment_filename" throughout the routes.py with "download_name".

Then the ssl-error.log gave me: **TypeError: send_file() got an unexpected keyword argument 'cache_timeout**.
Which is the next line under "attachment_filename" or now "download_name".

As suggested in this [github discussion](https://github.com/locustio/locust/pull/2148) I replaced "cache_timeout" with "max_age".

After that downloading Data from Experiments worked.</div>

**Comment by jobrachem** [comment]
For this issue, we should first investigate whether we need to take action. If yes, the steps described by Adsecularis will be helpful for resolving it.
